### ISSUE TITLE
How it works

### ISSUE THREAD

**Issue by Sciss** [kunstmusik/webaudio-csound-samples-example#1]
Hey Steven, just saw your project. I am currently trying something similar, i.e. putting online sound resources in a virtual file system in the browser for further DSP processing. Looking at App.js, I guess `fetch` just asynchronously transfers the resources into an in-memory byte buffer, or something like that? And `csound.writeToFS` then copies it to the virtual file system.

Do you have any pointers by chance on how to set up and use such virtual file system on the browser client-side? Is that something like https://developer.mozilla.org/en-US/docs/Web/API/FileSystem ?

Greetings

**Comment by kunstmusik** [comment]
Hi Hans Holger!  We are using Emscripten's FS implementation (https://emscripten.org/docs/api_reference/Filesystem-API.html) so that our native code can write/read as usual and Emscripten's FS takes care of the rest. We're using MEMFS so we have to recreate the FS each time but it has been working out well.  (Also used as part of the https://github.com/csound/web-ide). That's correct that fetch here is used to retrieve the resources, convert to bytes, then saved to the FS via writeToFS which ultimately calls Emscripten's FS functions. 

I had been talking to @Fr0stbyteR recently and I believe he's using https://github.com/jvilk/BrowserFS with IndexedDB backend to work with samples.  

Are you using WASM for DSP?

**Comment by Sciss** [comment]
Thanks. Although I hope I can use wasm at some point, it is not clear right now. Scala Native support for wasm is not official, and the steering group is not really interested in making it work. Similarly, SuperCollider steering group so far had no intention to dig into wasm; so in the meantime I'm experimenting with running the non-DSP parts and non-realtime-DSP parts of my computer music framework through JavaScript (Scala.js); I already managed to do some DSP in Scala.js, but probably performance is prohibitive for anything serious. But I'm interested in mixed realtime/non-realtime code, so being able to cache audio files offline is interesting to me, that's why I was asking. BrowserFS or direct IndexedDB might be a way for me.

**Comment by kunstmusik** [comment]
Ah, shame to hear SC group isn't looking at wasm, I think it's opened up a lot of interesting possibilities for us in the Csound community.  I hope the BrowserFS or IndexedDB works out for you!
